kind: ImageStream
apiVersion: v1
metadata:
  name: mule4-ee-jaeger
  annotations:
    openshift.io/display-name: "Mule 4 Runtime + Jaeger"
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule4-ee:latest-jaeger'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications with OpenJdk and Jaeger client instrumentation.\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version of the runtime.'
      openshift.io/display-name: Mule 4 Runtime (Latest) + Jaeger
      tags: runtime,mule,mule:4,integration,opentracing,jaeger
      supports: mule-ee:4,jaeger:0.29
  - name: '4.1.4'
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule4-ee:4.1.4-fedora-openjdk-jaeger'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications on the 4.1.4 runtime with OpenJdk and Jaeger instrumentation.'
      openshift.io/display-name: Mule 4.1.4 Runtime + Jaeger
      tags: mule,mule:4,integration,opentracing,jaeger
      supports: mule-ee:4,jaeger:0.29
      version: '4.1.4'
