#!/bin/sh

# Global S2I variable setup
source `dirname "$0"`/environment

# Tar up maven repository for reuse in an incremental build
if [ -d "${S2I_ARTIFACTS_DIR}/repository" ]; then
   cd ${S2I_ARTIFACTS_DIR}
   tar cf - ./repository
   cd -
fi
