kind: ImageStream
apiVersion: v1
metadata:
  name: mule-4-ee
  annotations:
    openshift.io/display-name: "Mule 4 Enterprise Edition Runtime"
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule-4-ee-centos:latest'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications with OpenJDK 11.\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version of the runtime.'
      openshift.io/display-name: Mule 4 Runtime (Latest)
      tags: runtime,mule,mule-4-ee,integration
      supports: mule-4-ee
  - name: '4.1.4-java8'
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule-4-ee-centos:4.1.4-java8'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications on the 4.1.4 runtime with OpenJDK 1.8.'
      openshift.io/display-name: Mule 4.1.4 Runtime
      tags: runtime,mule,mule-4-ee,integration
      supports: mule-4-ee:4.1.4
      version: '4.1.4'
  - name: '4.2.2-java8'
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule-4-ee-centos:4.2.2-java8'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications on the 4.2.2 runtime with OpenJDK 1.8.'
      openshift.io/display-name: Mule 4.2.2 Runtime
      tags: runtime,mule,mule-4-ee,integration
      supports: mule-4-ee:4.2.2
      version: '4.2.2'
  - name: '4.2.2-java11'
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule-4-ee-centos:4.2.2-java11'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications on the 4.2.2 runtime with OpenJDK 11.'
      openshift.io/display-name: Mule 4.2.2 Runtime
      tags: runtime,mule,mule-4-ee,integration
      supports: mule-4-ee:4.2.2
      version: '4.2.2'
  - name: '4.3.0-java8'
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule-4-ee-centos:4.3.0-java8'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications on the 4.3.0 runtime with OpenJDK 1.8.'
      openshift.io/display-name: Mule 4.3.0 Runtime
      tags: runtime,mule,mule-4-ee,integration
      supports: mule-4-ee:4.3.0
      version: '4.3.0'
  - name: '4.3.0-java11'
    from:
      kind: DockerImage
      name: 'quay.io/jam01/mule-4-ee-centos:4.3.0-java11'
    annotations:
      description: 'Run Mule 4 Enterprise Edition applications on the 4.3.0 runtime with OpenJDK 11.'
      openshift.io/display-name: Mule 4.3.0 Runtime
      tags: runtime,mule,mule-4-ee,integration
      supports: mule-4-ee:4.3.0
      version: '4.3.0'
